CREATE TABLE CATEGORIES (
    NUMCATEGORIE SERIAL PRIMARY KEY,
    LIBELLECATEGORIE VARCHAR(40) NOT NULL,
    CAT_NUMCATEGORIE2 INT,
    CONSTRAINT FK_CAT_NUMCATEGORIE2 FOREIGN KEY (CAT_NUMCATEGORIE2) REFERENCES CATEGORIES(NUMCATEGORIE)
);

CREATE TABLE REGLEAPPROVISIONNEMENT (
    NUMREGLE SERIAL PRIMARY KEY,
    SEUIL INT NOT NULL,
    MAXQTESTOCK INT NOT NULL,
    NUMARTICLE INT NOT NULL,
    CONSTRAINT FK_NUMARTICLE FOREIGN KEY (NUMARTICLE) REFERENCES ARTICLE(NUMARTICLE)
);

CREATE TABLE ARTICLE (
    NUMARTICLE SERIAL PRIMARY KEY,
    NOMARTICLE VARCHAR(50) NOT NULL,
    REFERENCEINTERNE CHAR(10) NOT NULL,
    PRIXVENTE DECIMAL(10,2) NOT NULL,
    COUTACHAT DECIMAL(10,2) NOT NULL,
    NUMCATEGORIE INT NOT NULL,
    CODETYPE CHAR(1) NOT NULL,
    CONSTRAINT FK_NUMCATEGORIE FOREIGN KEY (NUMCATEGORIE) REFERENCES CATEGORIES(NUMCATEGORIE),
    CONSTRAINT FK_CODETYPE FOREIGN KEY (CODETYPE) REFERENCES TYPEARTICLE(CODETYPE)
);

CREATE TABLE TYPEARTICLE (
    CODETYPE CHAR(1) PRIMARY KEY,
    LIBELLETYPE VARCHAR(40) NOT NULL
);

CREATE TABLE DETAILCOMMANDE (
    NUMCOMMANDE INT NOT NULL,
    NUMARTICLE INT NOT NULL,
    QUANTITECOMMANDEEE INT NOT NULL,
    QUANTITELIVREE INT NOT NULL,
    CONSTRAINT FK_NUMCOMMANDE FOREIGN KEY (NUMCOMMANDE) REFERENCES COMMANDE(NUMCOMMANDE),
    CONSTRAINT FK_NUMARTICLE FOREIGN KEY (NUMARTICLE) REFERENCES ARTICLE(NUMARTICLE),
    CONSTRAINT PK_DETAILCOMMANDE PRIMARY KEY (NUMCOMMANDE, NUMARTICLE)
);

CREATE TABLE COMMANDE (
    NUMCOMMANDE SERIAL PRIMARY KEY,
    NUMCLIENT INT NOT NULL,
    DATECOMMANDE DATE NOT NULL,
    MONTANTFRAIS NUMERIC(10,2) NOT NULL,
    MONTANTHT NUMERIC(10,2) NOT NULL,
    CONSTRAINT FK_NUMCLIENT FOREIGN KEY (NUMCLIENT) REFERENCES CLIENT(NUMCLIENT)
);

CREATE TABLE APPROVISIONNEMENT (
    NUMARTICLE INT NOT NULL,
    NUMPERSONNE INT NOT NULL,
    DELAILIVRAISON INT NOT NULL,
    PRIXACHAT DECIMAL(10,2) NOT NULL,
    CONSTRAINT FK_NUMARTICLE FOREIGN KEY (NUMARTICLE) REFERENCES ARTICLE(NUMARTICLE),
    CONSTRAINT FK_NUMPERSONNEL FOREIGN KEY (NUMPERSONNEL) REFERENCES PERSONNE(NUMPERSONNE),
    CONSTRAINT PK_APPROVISIONNEMENT PRIMARY KEY (NUMARTICLE, NUMPERSONNE)
);

CREATE TABLE PERSONNE (
    NUMPERSONNE SERIAL PRIMARY KEY,
    NOMPERSONNE VARCHAR(50) NOT NULL,
    ADRESSERUEPERSONNE VARCHAR(50) NOT NULL,
    ADRESSECODEPOSTALPERSONNE VARCHAR(10) NOT NULL,
    ADRESSEVILLEPERSONNE VARCHAR(40) NOT NULL,
    ADRESSEPAYSPERSONNE VARCHAR(30) NOT NULL,
    TELEPHONEPERSONNE VARCHAR(12) NOT NULL,
    MAILPERSONNE VARCHAR(60) NOT NULL,
    CONSTRAINT CHK_MAILPERSONNE CHECK (MAILPERSONNE LIKE '%@%')
);

CREATE TABLE FOURNISSEUR (
    NUMPERSONNE INT NOT NULL,
    CONSTRAINT FK_NUMPERSONNE FOREIGN KEY (NUMPERSONNE) REFERENCES PERSONNE(NUMPERSONNE),
    CONSTRAINT PK_FOURNISSEUR PRIMARY KEY (NUMPERSONNE)
)

CREATE TABLE CLIENT (
    NUMPERSONNE INT NOT NULL,
    CODELISTE CHAR(1) NOT NULL,
    CODEETIQUETTE CHAR(3) NOT NULL,
    CONSTRAINT FK_CODELISTE FOREIGN KEY (CODELISTE) REFERENCES LISTEPRIX(CODELISTE),
    CONSTRAINT FK_CODEETIQUETTE FOREIGN KEY (CODEETIQUETTE) REFERENCES ETIQUETTE(CODEETIQUETTE),
    CONSTRAINT FK_NUMPERSONNE FOREIGN KEY (NUMPERSONNE) REFERENCES PERSONNE(NUMPERSONNE),
    CONSTRAINT PK_CLIENT PRIMARY KEY (NUMPERSONNE)
)

CREATE TABLE CONTACT (
    NOM VARCHAR(50) NOT NULL,
    NUMPERSONNE int NOT NULL,
    TELEPHONE VARCHAR(12) NOT NULL,
    FONCTION VARCHAR(20) NOT NULL,
    CONSTRAINT FK_NUMPERSONNE FOREIGN KEY (NUMPERSONNE) REFERENCES PERSONNE(NUMPERSONNE),
    CONSTRAINT PK_CONTACT PRIMARY KEY (NOM, NUMPERSONNE)
);

CREATE TABLE ETIQUETTE (
    CODEETIQUETTE CHAR(3) PRIMARY KEY,
    LIBELLEETIQUETTE VARCHAR(70) NOT NULL,
    CODETYPETVA INT NOT NULL,
);

CREATE TABLE LISTEPRIX (
    CODELISTE CHAR(1) PRIMARY KEY,
    LIBELLELISTE VARCHAR(50) NOT NULL
);

CREATE TABLE TARIFVENTE (
    NUMARTICLE INT NOT NULL,
    CODELISTE CHAR(1) NOT NULL,
    PRIXVENTE  DECIMAL(10,2) NOT NULL,
    CONSTRAINT FK_NUMARTICLE FOREIGN KEY (NUMARTICLE) REFERENCES ARTICLE(NUMARTICLE),
    CONSTRAINT FK_CODELISTE FOREIGN KEY (CODELISTE) REFERENCES LISTEPRIX(CODELISTE),
    CONSTRAINT PK_TARIFVENTE PRIMARY KEY (NUMARTICLE, CODELISTE)
);

CREATE TABLE CARACTERISTIQUE (
    NOM VARCHAR(50) NOT NULL,
    CARACTERISTIQUE VARCHAR(50) NOT NULL,
    QUANTITESTOCK INT NOT NULL,
    CONSTRAINT FK_NOM FOREIGN KEY (NOM) REFERENCES ARTICLE(NOMARTICLE),
    CONSTRAINT PK_CARACTERISTIQUE PRIMARY KEY (NOM, CARACTERISTIQUE)
);